export enum RequestDestination {
    GEO_REVERSE_CODING_MAPPPING = 1,
    AUTOCOMPLETE_SUGGESTIONS_MAPPING = 2,
    PLACE_DETAILS_MAPPING = 3,
    IP_INFO_MAPPING = 4,
    PINCODES_DISTANCE_MAPPING=5,
    PARTNERS_DISTANCE_MAPPING=6,
};  