export const PARENT_API_STATUS = {
  PRODUCED: "PRODUCED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
};

export const CHILD_API_STATUS = {
  PRODUCED: "PRODUCED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
};

export const DATA_STORAGE_TYPES = {
  PDF: "pdf",
};
