export const COMPARATOR_PARENT_STATUS = {
  PRODUCED: "PRODUCED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
};

export const COMPARATOR_CHILD_STATUS = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNMATCHED: "UNMATCHED",
  MATCHED: "MATCHED",
  MISMATCHED: "MISMATCHED",
};
