export const PARENT_API_STATUS = {
  PRODUCED: "PRODUCED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
  RETRY: "RETRY",
};

export const CHILD_API_STATUS = {
  PRODUCED: "PRODUCED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
  RETRY: "RETRY",
};

export const PARENT_CONSUMER_PREFETCH_COUNT = 1;

export const CHILD_CONSUMER_PREFETCH_COUNT = 3;

export const ACCUMULATOR_CONSUMER_PREFETCH_COUNT = 1;

export const DATA_STORE_TYPES = {
  DATA: "data",
  XLSX: "xlsx",
};

export const ERROR_MESSAGES = {
  ARRAY_OR_OBJECT_TYPE_REQUIRED:
    "Invalid Type. Array or Object is the expected type",
};

export const TYPE_VS_ROUTING_KEY = {
  SLOW_TRANSACTION:
    process.env.RABBIT_MQ_UPLOAD_TRANSACTION_SLOW_CHILD_QUEUE_ROUTING_KEY,
  FAST_TRANSACTION:
    process.env.RABBIT_MQ_UPLOAD_TRANSACTION_FAST_CHILD_QUEUE_ROUTING_KEY,
  NON_TRANSACTIONAL:
    process.env.RABBIT_MQ_UPLOAD_NON_TRANSACTION_CHILD_QUEUE_ROUTING_KEY,
  RETRY: process.env.RABBIT_MQ_UPLOAD_RETRY_CHILD_QUEUE_ROUTING_KEY,
};
export const DEFAULT_SHEET_NAME_KEY = "sheet1";

export const MAX_EXECL_ROW_LENGTH = 1048576;

export const MAX_EXECL_COLUMN_LENGTH = 200;

export const INVALID_EMAIL_TEMPLATE = "UTILITY_ERROR_MAIL_INS";

export const DEFAULT_DELAY = 75;

export const DEFAULT_RETRY_DELAY = 2 * 1000;
