package com.leadonboardingservice.leadonboardingservice.enums;

public enum LeadEvent {
    PAN_UPLOADED, AADHAR_UPLOADED, PAN_REJECTED, PAN_APPROVED,
    GENERAL_TRAINING_MATERIAL_SHARED, GENERAL_TRAINING_MATERIAL_DOWNLOADED, GENERAL_TEST_LINK_SHARED, GENERAL_TEST_FAILED, GENERAL_AGREEMENT_PENDING, GENERAL_COMPLETED,
    LIFE_TRAINING_MATERIAL_SHARED, LIFE_TRAINING_MATERIAL_DOWNLOADED, LIFE_TEST_LINK_SHARED, LIFE_TEST_FAILED, LIFE_AGREEMENT_PENDING, LIFE_COMPLETED,
    CREATED, REGISTRATION_REQUESTED, DOCUMENTS_REUPLOAD_REQUIRED, REJECTED, CLOSED, VERIFIED, REGISTERED
}
