version: '3.3'

services:
  campaign-manager:
    build: .
    image: campaign-manager:1.0
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
