--liquibase formatted sql
--changeset pratiksha:leads_create_050920231437

ALTER TABLE leads
MODIFY COLUMN status ENUM('CREATED','REGISTRATION_REQUESTED','DOCUMENTS_REUPLOAD_REQUIRED','REJECTED','CLOSED','VERIFIED','REGISTERED','NOC_GIVEN') NOT NULL;
