export const TEMPLATES = {
  SMS_PAYMENT_LINK_TEMPLATE: "CUSTOMER_PAYMENT_LINK_SMS_INS",
  // ASSISTED_ONBOARDING: "OTPFORONBOARDING_INS",
};

export const SENDER = {
  SMS_PAYMENT_LINK: "CarIns",
};
