export const status = {
  ACTIVE: 1,
  INACTIVE: 0,
};

export const config = {
  SCORE_POPUP_VEHICLE_TYPES: "SCORE_POPUP_VEHICLE_TYPES",
  SCORE_POPUP_GCD_CODES: "SCORE_POPUP_GCD_CODES",
  SCORE_POPUP_PROD_READY: "SCORE_POPUP_PROD_READY",
  CASE_LISTING_PRODUCTS: "CASE_LISTING_PRODUCTS",
  CASE_LISTING_PRODUCT_FILTERS: "CASE_LISTING_PRODUCT_FILTERS",
  RENEWAL_PRODUCT_FILTERS: "RENEWAL_PRODUCT_FILTERS",
  CASE_LISTING_PROJECTION_FIELDS: "CASE_LISTING_PROJECTION_FIELDS",
  RENEWAL_PROJECTION_FIELDS: "RENEWAL_PROJECTION_FIELDS",
  SCORE_CARD_VISIBILITY: "SCORE_CARD_VISIBILITY",
  CASE_LISTING_ACTION_LINK: "CASE_LISTING_ACTION_LINK",
  SCORE_CARD_PRODUCT_CONFIG: "SCORE_CARD_PRODUCT_CONFIG",
  BANNER_CONFIG: "BANNER_CONFIG",
  SCORE_NAVBAR_CONFIG: "SCORE_NAVBAR_CONFIG",
  HOMEPAGE_POST_LOGIN: "HOMEPAGE_POST_LOGIN",
  KURUKSHETRA_HOMEPAGE: "KURUKSHETRA_HOMEPAGE",
  INSURANCE_LOBS: "INSURANCE_LOBS",
  INSURANCE_FUSION_LOBS: "INSURANCE_FUSION_LOBS",
  HEADER_FOOTER: "HEADER_FOOTER",
  REGNO_AUTOFILL_CONFIG: "REGNO_AUTOFILL_CONFIG",
  DEALER_DETAILS_BASIC_SKELETON: "DEALER_DETAILS_BASIC_SKELETON",
  DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
  FUSION_DASHBOARD_CONFIG: "FUSION_DASHBOARD_CONFIG",
  PARTNER_LISTING_CONFIG: "PARTNER_LISTING_CONFIG",
  QR_CODE: "QR_CODE",
  DUMMY_LEAD_ID: "6438e6f16ec4fd001d3180f4",
  PRODUCT_WISE_CHUNKS: "PRODUCT_WISE_CHUNKS",
  INSURER_WISE_LOGOS: "INSURER_WISE_LOGOS",
  CASE_LISTING_PRODUCTS_BASE_URLS: "CASE_LISTING_PRODUCTS_BASE_URLS",
  OTHER_PRODUCT_LOBS: "OTHER_PRODUCT_LOBS",
  NEW_QUOTE_PAGE_PERMISSION: "NEW_QUOTE_PAGE_PERMISSION",
  ELIGIBLE_RM_FOR_CREDIT_CARD: "ELIGIBLE_RM_FOR_CREDIT_CARD",
  BROKERAGE_PRODUCT_TYPE_MAPPING: "BROKERAGE_PRODUCT_TYPE_MAPPING",
  KYC_SORTING_ORDER: "KYC_SORTING_ORDER",
  KYC_INSURER_REDIRECTION_TAT: "KYC_INSURER_REDIRECTION_TAT",
  NEW_PROPOSAL_PAGE_REDIRECTION_CONFIG: "NEW_PROPOSAL_PAGE_REDIRECTION_CONFIG",
  FRAUD_MITIGATION: "FRAUD_MITIGATION",
  GRID_VISIBILITY: "GRID_VISIBILITY",
  SALES_DASHBOARD_CONFIG: "SALES_DASHBOARD_CONFIG",
  POS_LEAD_TO_POLICY_CONVERSION: "POS_LEAD_TO_POLICY_CONVERSION",
  JWT_CONFIG: "JWT_CONFIG",
  MOTOR_OFFLINE: "MOTOR_OFFLINE",
  PARTNER_EVENT: "PARTNER_EVENT",
  CROSS_SELL_CONFIG: "CROSS_SELL_CONFIG",
  ALTERNATE_PROPOSAL_FLOW: "ALTERNATE_PROPOSAL_FLOW",
};

export const CONFIG_CACHE_KEY = "__cacheKey__getConfigFromDb__";
export const FETCH_BANNER_CACHE_KEY = "__cacheKey__fetchBanner__";
export const LOGIN_SUPPORT_CREDENTIAL_CACHE_KEY =
  "__cacheKey__loginUserToSupport__";

export const CACHE_KEY = {
  BFF: "__cacheKey__",
  API_POS: "api_pos_",
  PAYMENT: "payment_",
};

export const ApiMode = {
  INSERT: "insert",
  UPDATE: "update",
  DELETE: "delete",
};

export const DataType = {
  JSON: "JSON",
};

export const ACCEPTED_PRODUCT_TYPE_FOR_CHUNKS = [
  "motor",
  "health",
  "onboarding",
];
export const ACCEPTED_RESOURCES = ["logos", "fonts"];

export const MAP_PRODUCT_TYPE_WITH_IDTREE_TEAM = {
  pet: "pet",
  travel: "travel",
  investment: "life",
  life: "life",
  wellness: "health",
  "personal-accident": "health",
  fire: "sme",
  sme: "sme",
  specificMarine: "sme",
  workmenCompensation: "sme",
  professionalIndemnity: "sme",
  home: "sme",
};

export const USER_REASON_FOR_DEACTIVATION_MAPPING = {
  FRADULENT_ACTIVITY: {
    STATUS: 1,
    DISPLAY_MESSAGE: "Fraudulent Activity",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  NEW_ACCOUNT_CREATION_REQUIRED: {
    STATUS: 2,
    DISPLAY_MESSAGE: "New account creation required",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  LEFT_THE_ORGANIZATION: {
    STATUS: 3,
    DISPLAY_MESSAGE: "Left the Organisation",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  JOINED_INSURANCE_COMPANY: {
    STATUS: 4,
    DISPLAY_MESSAGE: "Joined Insurance Company",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  DECEASED: {
    STATUS: 5,
    DISPLAY_MESSAGE: "Deceased",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  CLOSURE_DUE_TO_PAYOUT_ISSUE: {
    STATUS: 6,
    DISPLAY_MESSAGE: "Closure due to payout issue",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  RM_NOT_SUPPORTIVE: {
    STATUS: 7,
    DISPLAY_MESSAGE: "RM not supportive",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: true,
  },
  NOC_GIVEN: {
    STATUS: 8,
    DISPLAY_MESSAGE: "NOC Given",
    SHOW_IN_DROPDOWN: true,
    IS_UI_ACTIVATION_ALLOWED: false,
  },
  RE_REGISTRATION_PROCESS: {
    STATUS: 9,
    DISPLAY_MESSAGE: "In Re Registration Process",
    SHOW_IN_DROPDOWN: false,
    IS_UI_ACTIVATION_ALLOWED: false,
  },
};

export const CHATBOT_POLICY_PRODUCT = ["health"];
