export const PartnerListingProjections = [
  "gcd_code",
  "iam_uuid",
  "name",
  "health_NOP",
  "health_total_premium",
  "health_net_premium",
  "life_NOP",
  "life_total_premium",
  "life_net_premium",
  "motor_NOP",
  "motor_total_premium",
  "motor_net_premium",
  "overall_total_NOP",
  "overall_total_premium",
  "overall_net_premium",
  "pet_NOP",
  "pet_total_premium",
  "pet_net_premium",
  "travel_NOP",
  "travel_total_premium",
  "travel_net_premium",
  "sme_NOP",
  "sme_net_premium",
  "cc_leads_count",
  "cc_application_submitted_count",
  "cc_issued_count",
];

//  need another projections but try using the above projection only
export const PartnerListingProjectionsForRenewal = [
  "name",
  "gcd_code",
  "iam_uuid",
  "health_nop_renewed",
  "health_nop_to_be_renewed",
  "health_total_renewed_premium",
  "health_total_to_be_renewed_premium",
  "health_converted_premium_percent",
  "motor_nop_renewed",
  "motor_nop_to_be_renewed",
  "motor_total_renewed_premium",
  "motor_total_to_be_renewed_premium",
  "motor_converted_premium_percent",
];

export const mapRolesForPartnerListing = {
  1: "Admin",
  2: "SuperAdmin",
  3: "Dealer",
  4: "Dealer",
  8: "BM",
  9: "AM",
  10: "SH",
  11: "ZH",
  12: "NH",
  14: "SRM",
};
