export const SUPPORT_LOGIN_CREDENTIALS_CACHE_TIMEOUT = 86400;
export const ENDORSEMENT_TICKETS_FETCH_TIMEOUT = 7000;
export const ENDORSEMENT_DONE_STATUS = 4;
export const ENDORSEMENT_VISIBILITY_TIME_IN_DAYS = 7;
export const ISLAZY_LOAD_DEFAULT = 1;
export const ENDORSEMENT_TICKET_PAGE_DEFAULT = 1;
export const SUPPORT_CREDENTIALS_VALIDATE_TIMEOUT = 5000;

export const TicketType = {
  ENDORSEMENT: "endorsement",
};
