export const USER_DOC_LABEL_SLUG_MAP = {
  photo: "User Photo",
  x_certificate: "10th Certificate",
  aadhar_back: "Aadhar Back",
  aadhar_front: "Aadhar Front",
  pan: "PAN Card",
  cancel_cheque: "Cancel Cheque",
  life_certificate_v2: "Life Certificate",
  engagement_letter: "Engagement Letter",
  general_certificate_v2: "General Certificate",
  pan_noc: "PAN NOC",
  general_certificate_new: "General Certificate",
  life_certificate_new: "Life Certificate",
  opd_certificate_new: "OPD Certificate",
  general_certificate: "General Certificate",
  life_certificate: "Life Certificate",
  affidavit: "Affidavit",
  gstin_certificate: "GST IN Certificate",
  gcd_cancel_cheque: "Cancel Cheque",
  gcd_address_proof: "Address Proof",
  gcd_pan: "PAN",
  estamp: "E-Stamp with signed agreement",
};
