// OTP login
export const INITIATE_SEND_OTP = "INITIATE_SEND_OTP";
export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const SEND_LOGIN_OTP = "SEND_LOGIN_OTP";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_FAILED = "OTP_SEND_FAILED";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILED = "OTP_VERIFY_FAILED";
export const CHANGE_NUMBER = "CHANGE_NUMBER";
export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const EMIT_LOGIN_EVENT = "EMIT_LOGIN_EVENT";
export const GENERATE_GOOGLE_RECAPTCHA_TOKEN =
  "GENERATE_GOOGLE_RECAPTCHA_TOKEN";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_RESET = "OTP_LOGIN_RESET";
export const OTP_LOGIN_FAILED = "OTP_LOGIN_FAILED";

// Google login
export const VALIDATE_GOOGLE_LOGIN = "VALIDATE_GOOGLE_LOGIN";
export const GOOGLE_VERIFY_SUCCESS = "GOOGLE_VERIFY_SUCCESS";
export const GOOGLE_VERIFY_FAILED = "GOOGLE_VERIFY_FAILED";

export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_RESET = "GOOGLE_LOGIN_RESET";
export const GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED";

//logout
export const INITIATE_LOGOUT = "INITIATE_LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_RESET = "LOGOUT_RESET";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//common
export const SET_MODULE_OPTIONS = "SET_MODULE_OPTIONS";

//Learning Module
export const GET_CONTENT = "GET_CONTENT";
export const SET_CONTENT = "SET_CONTENT";
export const GET_COMPLETION_STATUS = "GET_COMPLETION_STATUS";
export const SET_COMPLETION_STATUS = "SET_COMPLETION_STATUS";
export const UPDATE_COMPLETION_STATUS = "UPDATE_COMPLETION_STATUS";
export const GET_ENTIRE_CONTENT = "GET_ENTIRE_CONTENT";
export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";

//Promotional Banner Module
export const GET_BANNER = "GET_BANNER";
export const SET_BANNER = "SET_BANNER";
export const GET_CUSTOM_BANNER = "GET_CUSTOM_BANNER";
export const SET_CUSTOM_BANNER = "SET_CUSTOM_BANNER";
export const RESET_CUSTOM_BANNER = "RESET_CUSTOM_BANNER";
export const ADD_BANNER = "ADD_BANNER";
export const DELETE_BANNER = "DELETE_BANNER";
export const EDIT_BANNER = "EDIT_BANNER";

//React form builder
export const INIT_RFB = "INIT_RFB";
export const UPDATE_FIELD_VALUE = "UPDATE_FIELD_VALUE";
export const VALIDATE_FIELD_VALUE = "VALIDATE_FIELD_VALUE";
export const VALIDATE_SUBMIT_FORM_STEP = "VALIDATE_SUBMIT_FORM_STEP";
export const HANDLE_SUBMIT_SUCCESS = "HANDLE_SUBMIT_SUCCESS";
export const HANDLE_SUBMIT_FAILURE = "HANDLE_SUBMIT_FAILURE";
export const UPDATE_STEP = "UPDATE_STEP";
export const GO_BACK = "GO_BACK";
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";