export const GET_ID_EXCLUSIVE_BANNER = "GET_ID_EXCLUSIVE_BANNER";
export const SET_ID_EXCLUSIVE_BANNER = "SET_ID_EXCLUSIVE_BANNER";
export const ADD_ID_EXCLUSIVE_BANNER = "ADD_ID_EXCLUSIVE_BANNER";
export const ADD_ID_EXCLUSIVE_BANNER_STATUS = "ADD_ID_EXCLUSIVE_BANNER_STATUS";
export const DELETE_ID_EXCLUSIVE_BANNER = "DELETE_ID_EXCLUSIVE_BANNER";
export const EDIT_ID_EXCLUSIVE_BANNER = "EDIT_ID_EXCLUSIVE_BANNER";
export const EDIT_ID_EXCLUSIVE_BANNER_STATUS =
  "EDIT_ID_EXCLUSIVE_BANNER_STATUS";
export const DELETE_ID_EXCLUSIVE_BANNER_STATUS =
  "DELETE_ID_EXCLUSIVE_BANNER_STATUS";
export const GET_TENANTS_LIST = "GET_TENANTS_LIST";
export const SET_TENANTS_LIST = "SET_TENANTS_LIST";
